// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/vision.proto
#ifndef GRPC_proto_2fvision_2eproto__INCLUDED
#define GRPC_proto_2fvision_2eproto__INCLUDED

#include "proto/vision.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace surveillance {
namespace vision {

// Service principal de traitement vidéo
class VisionService final {
 public:
  static constexpr char const* service_full_name() {
    return "surveillance.vision.VisionService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Démarrer un stream de caméra
    virtual ::grpc::Status StartStream(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest& request, ::surveillance::vision::StreamResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StreamResponse>> AsyncStartStream(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StreamResponse>>(AsyncStartStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StreamResponse>> PrepareAsyncStartStream(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StreamResponse>>(PrepareAsyncStartStreamRaw(context, request, cq));
    }
    // Arrêter un stream de caméra  
    virtual ::grpc::Status StopStream(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest& request, ::surveillance::vision::StopResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StopResponse>> AsyncStopStream(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StopResponse>>(AsyncStopStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StopResponse>> PrepareAsyncStopStream(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StopResponse>>(PrepareAsyncStopStreamRaw(context, request, cq));
    }
    // Récupérer le statut d'un stream
    virtual ::grpc::Status GetStreamStatus(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest& request, ::surveillance::vision::StatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StatusResponse>> AsyncGetStreamStatus(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StatusResponse>>(AsyncGetStreamStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StatusResponse>> PrepareAsyncGetStreamStatus(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StatusResponse>>(PrepareAsyncGetStreamStatusRaw(context, request, cq));
    }
    // Health check du service
    virtual ::grpc::Status GetHealth(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest& request, ::surveillance::vision::HealthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::HealthResponse>> AsyncGetHealth(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::HealthResponse>>(AsyncGetHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::HealthResponse>> PrepareAsyncGetHealth(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::HealthResponse>>(PrepareAsyncGetHealthRaw(context, request, cq));
    }
    // Stream de frames (bidirectionnel)
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>> ProcessFrames(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>>(ProcessFramesRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>> AsyncProcessFrames(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>>(AsyncProcessFramesRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>> PrepareAsyncProcessFrames(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>>(PrepareAsyncProcessFramesRaw(context, cq));
    }
    // Récupérer une frame du buffer (server-side streaming)
    std::unique_ptr< ::grpc::ClientReaderInterface< ::surveillance::vision::Frame>> GetFrames(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::surveillance::vision::Frame>>(GetFramesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::surveillance::vision::Frame>> AsyncGetFrames(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::surveillance::vision::Frame>>(AsyncGetFramesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::surveillance::vision::Frame>> PrepareAsyncGetFrames(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::surveillance::vision::Frame>>(PrepareAsyncGetFramesRaw(context, request, cq));
    }
    // Stream des événements de détection (server-side streaming)
    std::unique_ptr< ::grpc::ClientReaderInterface< ::surveillance::vision::DetectionEvent>> StreamDetections(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::surveillance::vision::DetectionEvent>>(StreamDetectionsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::surveillance::vision::DetectionEvent>> AsyncStreamDetections(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::surveillance::vision::DetectionEvent>>(AsyncStreamDetectionsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::surveillance::vision::DetectionEvent>> PrepareAsyncStreamDetections(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::surveillance::vision::DetectionEvent>>(PrepareAsyncStreamDetectionsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Démarrer un stream de caméra
      virtual void StartStream(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest* request, ::surveillance::vision::StreamResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StartStream(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest* request, ::surveillance::vision::StreamResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Arrêter un stream de caméra  
      virtual void StopStream(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest* request, ::surveillance::vision::StopResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void StopStream(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest* request, ::surveillance::vision::StopResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Récupérer le statut d'un stream
      virtual void GetStreamStatus(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest* request, ::surveillance::vision::StatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetStreamStatus(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest* request, ::surveillance::vision::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Health check du service
      virtual void GetHealth(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest* request, ::surveillance::vision::HealthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetHealth(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest* request, ::surveillance::vision::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Stream de frames (bidirectionnel)
      virtual void ProcessFrames(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::surveillance::vision::FrameRequest,::surveillance::vision::FrameResponse>* reactor) = 0;
      // Récupérer une frame du buffer (server-side streaming)
      virtual void GetFrames(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest* request, ::grpc::ClientReadReactor< ::surveillance::vision::Frame>* reactor) = 0;
      // Stream des événements de détection (server-side streaming)
      virtual void StreamDetections(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest* request, ::grpc::ClientReadReactor< ::surveillance::vision::DetectionEvent>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StreamResponse>* AsyncStartStreamRaw(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StreamResponse>* PrepareAsyncStartStreamRaw(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StopResponse>* AsyncStopStreamRaw(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StopResponse>* PrepareAsyncStopStreamRaw(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StatusResponse>* AsyncGetStreamStatusRaw(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::StatusResponse>* PrepareAsyncGetStreamStatusRaw(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::HealthResponse>* AsyncGetHealthRaw(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::surveillance::vision::HealthResponse>* PrepareAsyncGetHealthRaw(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>* ProcessFramesRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>* AsyncProcessFramesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>* PrepareAsyncProcessFramesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::surveillance::vision::Frame>* GetFramesRaw(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::surveillance::vision::Frame>* AsyncGetFramesRaw(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::surveillance::vision::Frame>* PrepareAsyncGetFramesRaw(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::surveillance::vision::DetectionEvent>* StreamDetectionsRaw(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::surveillance::vision::DetectionEvent>* AsyncStreamDetectionsRaw(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::surveillance::vision::DetectionEvent>* PrepareAsyncStreamDetectionsRaw(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status StartStream(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest& request, ::surveillance::vision::StreamResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StreamResponse>> AsyncStartStream(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StreamResponse>>(AsyncStartStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StreamResponse>> PrepareAsyncStartStream(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StreamResponse>>(PrepareAsyncStartStreamRaw(context, request, cq));
    }
    ::grpc::Status StopStream(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest& request, ::surveillance::vision::StopResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StopResponse>> AsyncStopStream(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StopResponse>>(AsyncStopStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StopResponse>> PrepareAsyncStopStream(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StopResponse>>(PrepareAsyncStopStreamRaw(context, request, cq));
    }
    ::grpc::Status GetStreamStatus(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest& request, ::surveillance::vision::StatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StatusResponse>> AsyncGetStreamStatus(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StatusResponse>>(AsyncGetStreamStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StatusResponse>> PrepareAsyncGetStreamStatus(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StatusResponse>>(PrepareAsyncGetStreamStatusRaw(context, request, cq));
    }
    ::grpc::Status GetHealth(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest& request, ::surveillance::vision::HealthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::HealthResponse>> AsyncGetHealth(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::HealthResponse>>(AsyncGetHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::HealthResponse>> PrepareAsyncGetHealth(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::surveillance::vision::HealthResponse>>(PrepareAsyncGetHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>> ProcessFrames(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>>(ProcessFramesRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>> AsyncProcessFrames(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>>(AsyncProcessFramesRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>> PrepareAsyncProcessFrames(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>>(PrepareAsyncProcessFramesRaw(context, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::surveillance::vision::Frame>> GetFrames(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::surveillance::vision::Frame>>(GetFramesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::surveillance::vision::Frame>> AsyncGetFrames(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::surveillance::vision::Frame>>(AsyncGetFramesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::surveillance::vision::Frame>> PrepareAsyncGetFrames(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::surveillance::vision::Frame>>(PrepareAsyncGetFramesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::surveillance::vision::DetectionEvent>> StreamDetections(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::surveillance::vision::DetectionEvent>>(StreamDetectionsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::surveillance::vision::DetectionEvent>> AsyncStreamDetections(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::surveillance::vision::DetectionEvent>>(AsyncStreamDetectionsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::surveillance::vision::DetectionEvent>> PrepareAsyncStreamDetections(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::surveillance::vision::DetectionEvent>>(PrepareAsyncStreamDetectionsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StartStream(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest* request, ::surveillance::vision::StreamResponse* response, std::function<void(::grpc::Status)>) override;
      void StartStream(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest* request, ::surveillance::vision::StreamResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StopStream(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest* request, ::surveillance::vision::StopResponse* response, std::function<void(::grpc::Status)>) override;
      void StopStream(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest* request, ::surveillance::vision::StopResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetStreamStatus(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest* request, ::surveillance::vision::StatusResponse* response, std::function<void(::grpc::Status)>) override;
      void GetStreamStatus(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest* request, ::surveillance::vision::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetHealth(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest* request, ::surveillance::vision::HealthResponse* response, std::function<void(::grpc::Status)>) override;
      void GetHealth(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest* request, ::surveillance::vision::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ProcessFrames(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::surveillance::vision::FrameRequest,::surveillance::vision::FrameResponse>* reactor) override;
      void GetFrames(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest* request, ::grpc::ClientReadReactor< ::surveillance::vision::Frame>* reactor) override;
      void StreamDetections(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest* request, ::grpc::ClientReadReactor< ::surveillance::vision::DetectionEvent>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StreamResponse>* AsyncStartStreamRaw(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StreamResponse>* PrepareAsyncStartStreamRaw(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StopResponse>* AsyncStopStreamRaw(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StopResponse>* PrepareAsyncStopStreamRaw(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StatusResponse>* AsyncGetStreamStatusRaw(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::surveillance::vision::StatusResponse>* PrepareAsyncGetStreamStatusRaw(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::surveillance::vision::HealthResponse>* AsyncGetHealthRaw(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::surveillance::vision::HealthResponse>* PrepareAsyncGetHealthRaw(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>* ProcessFramesRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>* AsyncProcessFramesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>* PrepareAsyncProcessFramesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::surveillance::vision::Frame>* GetFramesRaw(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request) override;
    ::grpc::ClientAsyncReader< ::surveillance::vision::Frame>* AsyncGetFramesRaw(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::surveillance::vision::Frame>* PrepareAsyncGetFramesRaw(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::surveillance::vision::DetectionEvent>* StreamDetectionsRaw(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request) override;
    ::grpc::ClientAsyncReader< ::surveillance::vision::DetectionEvent>* AsyncStreamDetectionsRaw(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::surveillance::vision::DetectionEvent>* PrepareAsyncStreamDetectionsRaw(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StartStream_;
    const ::grpc::internal::RpcMethod rpcmethod_StopStream_;
    const ::grpc::internal::RpcMethod rpcmethod_GetStreamStatus_;
    const ::grpc::internal::RpcMethod rpcmethod_GetHealth_;
    const ::grpc::internal::RpcMethod rpcmethod_ProcessFrames_;
    const ::grpc::internal::RpcMethod rpcmethod_GetFrames_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamDetections_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Démarrer un stream de caméra
    virtual ::grpc::Status StartStream(::grpc::ServerContext* context, const ::surveillance::vision::StreamRequest* request, ::surveillance::vision::StreamResponse* response);
    // Arrêter un stream de caméra  
    virtual ::grpc::Status StopStream(::grpc::ServerContext* context, const ::surveillance::vision::StopRequest* request, ::surveillance::vision::StopResponse* response);
    // Récupérer le statut d'un stream
    virtual ::grpc::Status GetStreamStatus(::grpc::ServerContext* context, const ::surveillance::vision::StatusRequest* request, ::surveillance::vision::StatusResponse* response);
    // Health check du service
    virtual ::grpc::Status GetHealth(::grpc::ServerContext* context, const ::surveillance::vision::HealthRequest* request, ::surveillance::vision::HealthResponse* response);
    // Stream de frames (bidirectionnel)
    virtual ::grpc::Status ProcessFrames(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::surveillance::vision::FrameResponse, ::surveillance::vision::FrameRequest>* stream);
    // Récupérer une frame du buffer (server-side streaming)
    virtual ::grpc::Status GetFrames(::grpc::ServerContext* context, const ::surveillance::vision::GetFramesRequest* request, ::grpc::ServerWriter< ::surveillance::vision::Frame>* writer);
    // Stream des événements de détection (server-side streaming)
    virtual ::grpc::Status StreamDetections(::grpc::ServerContext* context, const ::surveillance::vision::DetectionStreamRequest* request, ::grpc::ServerWriter< ::surveillance::vision::DetectionEvent>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_StartStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StartStream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StartStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartStream(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StreamRequest* /*request*/, ::surveillance::vision::StreamResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartStream(::grpc::ServerContext* context, ::surveillance::vision::StreamRequest* request, ::grpc::ServerAsyncResponseWriter< ::surveillance::vision::StreamResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StopStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StopStream() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_StopStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopStream(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StopRequest* /*request*/, ::surveillance::vision::StopResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStopStream(::grpc::ServerContext* context, ::surveillance::vision::StopRequest* request, ::grpc::ServerAsyncResponseWriter< ::surveillance::vision::StopResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetStreamStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetStreamStatus() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetStreamStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStreamStatus(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StatusRequest* /*request*/, ::surveillance::vision::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStreamStatus(::grpc::ServerContext* context, ::surveillance::vision::StatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::surveillance::vision::StatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetHealth() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHealth(::grpc::ServerContext* /*context*/, const ::surveillance::vision::HealthRequest* /*request*/, ::surveillance::vision::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetHealth(::grpc::ServerContext* context, ::surveillance::vision::HealthRequest* request, ::grpc::ServerAsyncResponseWriter< ::surveillance::vision::HealthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ProcessFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ProcessFrames() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_ProcessFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessFrames(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::surveillance::vision::FrameResponse, ::surveillance::vision::FrameRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessFrames(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::surveillance::vision::FrameResponse, ::surveillance::vision::FrameRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(4, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetFrames() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_GetFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFrames(::grpc::ServerContext* /*context*/, const ::surveillance::vision::GetFramesRequest* /*request*/, ::grpc::ServerWriter< ::surveillance::vision::Frame>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFrames(::grpc::ServerContext* context, ::surveillance::vision::GetFramesRequest* request, ::grpc::ServerAsyncWriter< ::surveillance::vision::Frame>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(5, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamDetections : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamDetections() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_StreamDetections() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamDetections(::grpc::ServerContext* /*context*/, const ::surveillance::vision::DetectionStreamRequest* /*request*/, ::grpc::ServerWriter< ::surveillance::vision::DetectionEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamDetections(::grpc::ServerContext* context, ::surveillance::vision::DetectionStreamRequest* request, ::grpc::ServerAsyncWriter< ::surveillance::vision::DetectionEvent>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(6, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StartStream<WithAsyncMethod_StopStream<WithAsyncMethod_GetStreamStatus<WithAsyncMethod_GetHealth<WithAsyncMethod_ProcessFrames<WithAsyncMethod_GetFrames<WithAsyncMethod_StreamDetections<Service > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StartStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StartStream() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::surveillance::vision::StreamRequest, ::surveillance::vision::StreamResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::surveillance::vision::StreamRequest* request, ::surveillance::vision::StreamResponse* response) { return this->StartStream(context, request, response); }));}
    void SetMessageAllocatorFor_StartStream(
        ::grpc::MessageAllocator< ::surveillance::vision::StreamRequest, ::surveillance::vision::StreamResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::surveillance::vision::StreamRequest, ::surveillance::vision::StreamResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StartStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartStream(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StreamRequest* /*request*/, ::surveillance::vision::StreamResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StartStream(
      ::grpc::CallbackServerContext* /*context*/, const ::surveillance::vision::StreamRequest* /*request*/, ::surveillance::vision::StreamResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StopStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StopStream() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::surveillance::vision::StopRequest, ::surveillance::vision::StopResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::surveillance::vision::StopRequest* request, ::surveillance::vision::StopResponse* response) { return this->StopStream(context, request, response); }));}
    void SetMessageAllocatorFor_StopStream(
        ::grpc::MessageAllocator< ::surveillance::vision::StopRequest, ::surveillance::vision::StopResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::surveillance::vision::StopRequest, ::surveillance::vision::StopResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_StopStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopStream(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StopRequest* /*request*/, ::surveillance::vision::StopResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StopStream(
      ::grpc::CallbackServerContext* /*context*/, const ::surveillance::vision::StopRequest* /*request*/, ::surveillance::vision::StopResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetStreamStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetStreamStatus() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::surveillance::vision::StatusRequest, ::surveillance::vision::StatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::surveillance::vision::StatusRequest* request, ::surveillance::vision::StatusResponse* response) { return this->GetStreamStatus(context, request, response); }));}
    void SetMessageAllocatorFor_GetStreamStatus(
        ::grpc::MessageAllocator< ::surveillance::vision::StatusRequest, ::surveillance::vision::StatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::surveillance::vision::StatusRequest, ::surveillance::vision::StatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetStreamStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStreamStatus(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StatusRequest* /*request*/, ::surveillance::vision::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetStreamStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::surveillance::vision::StatusRequest* /*request*/, ::surveillance::vision::StatusResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetHealth() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::surveillance::vision::HealthRequest, ::surveillance::vision::HealthResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::surveillance::vision::HealthRequest* request, ::surveillance::vision::HealthResponse* response) { return this->GetHealth(context, request, response); }));}
    void SetMessageAllocatorFor_GetHealth(
        ::grpc::MessageAllocator< ::surveillance::vision::HealthRequest, ::surveillance::vision::HealthResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::surveillance::vision::HealthRequest, ::surveillance::vision::HealthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHealth(::grpc::ServerContext* /*context*/, const ::surveillance::vision::HealthRequest* /*request*/, ::surveillance::vision::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetHealth(
      ::grpc::CallbackServerContext* /*context*/, const ::surveillance::vision::HealthRequest* /*request*/, ::surveillance::vision::HealthResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ProcessFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ProcessFrames() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackBidiHandler< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ProcessFrames(context); }));
    }
    ~WithCallbackMethod_ProcessFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessFrames(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::surveillance::vision::FrameResponse, ::surveillance::vision::FrameRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>* ProcessFrames(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetFrames() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackServerStreamingHandler< ::surveillance::vision::GetFramesRequest, ::surveillance::vision::Frame>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::surveillance::vision::GetFramesRequest* request) { return this->GetFrames(context, request); }));
    }
    ~WithCallbackMethod_GetFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFrames(::grpc::ServerContext* /*context*/, const ::surveillance::vision::GetFramesRequest* /*request*/, ::grpc::ServerWriter< ::surveillance::vision::Frame>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::surveillance::vision::Frame>* GetFrames(
      ::grpc::CallbackServerContext* /*context*/, const ::surveillance::vision::GetFramesRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamDetections : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamDetections() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackServerStreamingHandler< ::surveillance::vision::DetectionStreamRequest, ::surveillance::vision::DetectionEvent>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::surveillance::vision::DetectionStreamRequest* request) { return this->StreamDetections(context, request); }));
    }
    ~WithCallbackMethod_StreamDetections() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamDetections(::grpc::ServerContext* /*context*/, const ::surveillance::vision::DetectionStreamRequest* /*request*/, ::grpc::ServerWriter< ::surveillance::vision::DetectionEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::surveillance::vision::DetectionEvent>* StreamDetections(
      ::grpc::CallbackServerContext* /*context*/, const ::surveillance::vision::DetectionStreamRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StartStream<WithCallbackMethod_StopStream<WithCallbackMethod_GetStreamStatus<WithCallbackMethod_GetHealth<WithCallbackMethod_ProcessFrames<WithCallbackMethod_GetFrames<WithCallbackMethod_StreamDetections<Service > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StartStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StartStream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StartStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartStream(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StreamRequest* /*request*/, ::surveillance::vision::StreamResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StopStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StopStream() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_StopStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopStream(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StopRequest* /*request*/, ::surveillance::vision::StopResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetStreamStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetStreamStatus() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetStreamStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStreamStatus(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StatusRequest* /*request*/, ::surveillance::vision::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetHealth() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHealth(::grpc::ServerContext* /*context*/, const ::surveillance::vision::HealthRequest* /*request*/, ::surveillance::vision::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ProcessFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ProcessFrames() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_ProcessFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessFrames(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::surveillance::vision::FrameResponse, ::surveillance::vision::FrameRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetFrames() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_GetFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFrames(::grpc::ServerContext* /*context*/, const ::surveillance::vision::GetFramesRequest* /*request*/, ::grpc::ServerWriter< ::surveillance::vision::Frame>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamDetections : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamDetections() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_StreamDetections() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamDetections(::grpc::ServerContext* /*context*/, const ::surveillance::vision::DetectionStreamRequest* /*request*/, ::grpc::ServerWriter< ::surveillance::vision::DetectionEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StartStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StartStream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StartStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartStream(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StreamRequest* /*request*/, ::surveillance::vision::StreamResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStartStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StopStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StopStream() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_StopStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopStream(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StopRequest* /*request*/, ::surveillance::vision::StopResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStopStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetStreamStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetStreamStatus() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetStreamStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStreamStatus(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StatusRequest* /*request*/, ::surveillance::vision::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStreamStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetHealth() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHealth(::grpc::ServerContext* /*context*/, const ::surveillance::vision::HealthRequest* /*request*/, ::surveillance::vision::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetHealth(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ProcessFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ProcessFrames() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_ProcessFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessFrames(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::surveillance::vision::FrameResponse, ::surveillance::vision::FrameRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessFrames(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(4, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetFrames() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_GetFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFrames(::grpc::ServerContext* /*context*/, const ::surveillance::vision::GetFramesRequest* /*request*/, ::grpc::ServerWriter< ::surveillance::vision::Frame>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFrames(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(5, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamDetections : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamDetections() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_StreamDetections() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamDetections(::grpc::ServerContext* /*context*/, const ::surveillance::vision::DetectionStreamRequest* /*request*/, ::grpc::ServerWriter< ::surveillance::vision::DetectionEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamDetections(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(6, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StartStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StartStream() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StartStream(context, request, response); }));
    }
    ~WithRawCallbackMethod_StartStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StartStream(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StreamRequest* /*request*/, ::surveillance::vision::StreamResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StartStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StopStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StopStream() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->StopStream(context, request, response); }));
    }
    ~WithRawCallbackMethod_StopStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StopStream(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StopRequest* /*request*/, ::surveillance::vision::StopResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* StopStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetStreamStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetStreamStatus() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetStreamStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetStreamStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStreamStatus(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StatusRequest* /*request*/, ::surveillance::vision::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetStreamStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetHealth() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetHealth(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHealth(::grpc::ServerContext* /*context*/, const ::surveillance::vision::HealthRequest* /*request*/, ::surveillance::vision::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetHealth(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ProcessFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ProcessFrames() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ProcessFrames(context); }));
    }
    ~WithRawCallbackMethod_ProcessFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessFrames(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::surveillance::vision::FrameResponse, ::surveillance::vision::FrameRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* ProcessFrames(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetFrames() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->GetFrames(context, request); }));
    }
    ~WithRawCallbackMethod_GetFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFrames(::grpc::ServerContext* /*context*/, const ::surveillance::vision::GetFramesRequest* /*request*/, ::grpc::ServerWriter< ::surveillance::vision::Frame>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* GetFrames(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamDetections : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamDetections() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamDetections(context, request); }));
    }
    ~WithRawCallbackMethod_StreamDetections() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamDetections(::grpc::ServerContext* /*context*/, const ::surveillance::vision::DetectionStreamRequest* /*request*/, ::grpc::ServerWriter< ::surveillance::vision::DetectionEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamDetections(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StartStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StartStream() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::surveillance::vision::StreamRequest, ::surveillance::vision::StreamResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::surveillance::vision::StreamRequest, ::surveillance::vision::StreamResponse>* streamer) {
                       return this->StreamedStartStream(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StartStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StartStream(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StreamRequest* /*request*/, ::surveillance::vision::StreamResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStartStream(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::surveillance::vision::StreamRequest,::surveillance::vision::StreamResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_StopStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_StopStream() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::surveillance::vision::StopRequest, ::surveillance::vision::StopResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::surveillance::vision::StopRequest, ::surveillance::vision::StopResponse>* streamer) {
                       return this->StreamedStopStream(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_StopStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StopStream(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StopRequest* /*request*/, ::surveillance::vision::StopResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedStopStream(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::surveillance::vision::StopRequest,::surveillance::vision::StopResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetStreamStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetStreamStatus() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::surveillance::vision::StatusRequest, ::surveillance::vision::StatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::surveillance::vision::StatusRequest, ::surveillance::vision::StatusResponse>* streamer) {
                       return this->StreamedGetStreamStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetStreamStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetStreamStatus(::grpc::ServerContext* /*context*/, const ::surveillance::vision::StatusRequest* /*request*/, ::surveillance::vision::StatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetStreamStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::surveillance::vision::StatusRequest,::surveillance::vision::StatusResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetHealth() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::surveillance::vision::HealthRequest, ::surveillance::vision::HealthResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::surveillance::vision::HealthRequest, ::surveillance::vision::HealthResponse>* streamer) {
                       return this->StreamedGetHealth(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetHealth(::grpc::ServerContext* /*context*/, const ::surveillance::vision::HealthRequest* /*request*/, ::surveillance::vision::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetHealth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::surveillance::vision::HealthRequest,::surveillance::vision::HealthResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_StartStream<WithStreamedUnaryMethod_StopStream<WithStreamedUnaryMethod_GetStreamStatus<WithStreamedUnaryMethod_GetHealth<Service > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_GetFrames : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_GetFrames() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::surveillance::vision::GetFramesRequest, ::surveillance::vision::Frame>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::surveillance::vision::GetFramesRequest, ::surveillance::vision::Frame>* streamer) {
                       return this->StreamedGetFrames(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_GetFrames() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetFrames(::grpc::ServerContext* /*context*/, const ::surveillance::vision::GetFramesRequest* /*request*/, ::grpc::ServerWriter< ::surveillance::vision::Frame>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedGetFrames(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::surveillance::vision::GetFramesRequest,::surveillance::vision::Frame>* server_split_streamer) = 0;
  };
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamDetections : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamDetections() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::surveillance::vision::DetectionStreamRequest, ::surveillance::vision::DetectionEvent>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::surveillance::vision::DetectionStreamRequest, ::surveillance::vision::DetectionEvent>* streamer) {
                       return this->StreamedStreamDetections(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamDetections() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamDetections(::grpc::ServerContext* /*context*/, const ::surveillance::vision::DetectionStreamRequest* /*request*/, ::grpc::ServerWriter< ::surveillance::vision::DetectionEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamDetections(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::surveillance::vision::DetectionStreamRequest,::surveillance::vision::DetectionEvent>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_GetFrames<WithSplitStreamingMethod_StreamDetections<Service > > SplitStreamedService;
  typedef WithStreamedUnaryMethod_StartStream<WithStreamedUnaryMethod_StopStream<WithStreamedUnaryMethod_GetStreamStatus<WithStreamedUnaryMethod_GetHealth<WithSplitStreamingMethod_GetFrames<WithSplitStreamingMethod_StreamDetections<Service > > > > > > StreamedService;
};

}  // namespace vision
}  // namespace surveillance


#endif  // GRPC_proto_2fvision_2eproto__INCLUDED
