// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/vision.proto

#include "proto/vision.pb.h"
#include "proto/vision.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace surveillance {
namespace vision {

static const char* VisionService_method_names[] = {
  "/surveillance.vision.VisionService/StartStream",
  "/surveillance.vision.VisionService/StopStream",
  "/surveillance.vision.VisionService/GetStreamStatus",
  "/surveillance.vision.VisionService/GetHealth",
  "/surveillance.vision.VisionService/ProcessFrames",
  "/surveillance.vision.VisionService/GetFrames",
  "/surveillance.vision.VisionService/StreamDetections",
};

std::unique_ptr< VisionService::Stub> VisionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VisionService::Stub> stub(new VisionService::Stub(channel, options));
  return stub;
}

VisionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StartStream_(VisionService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopStream_(VisionService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStreamStatus_(VisionService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetHealth_(VisionService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ProcessFrames_(VisionService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_GetFrames_(VisionService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_StreamDetections_(VisionService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status VisionService::Stub::StartStream(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest& request, ::surveillance::vision::StreamResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::surveillance::vision::StreamRequest, ::surveillance::vision::StreamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartStream_, context, request, response);
}

void VisionService::Stub::async::StartStream(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest* request, ::surveillance::vision::StreamResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::surveillance::vision::StreamRequest, ::surveillance::vision::StreamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartStream_, context, request, response, std::move(f));
}

void VisionService::Stub::async::StartStream(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest* request, ::surveillance::vision::StreamResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartStream_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::surveillance::vision::StreamResponse>* VisionService::Stub::PrepareAsyncStartStreamRaw(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::surveillance::vision::StreamResponse, ::surveillance::vision::StreamRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartStream_, context, request);
}

::grpc::ClientAsyncResponseReader< ::surveillance::vision::StreamResponse>* VisionService::Stub::AsyncStartStreamRaw(::grpc::ClientContext* context, const ::surveillance::vision::StreamRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartStreamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VisionService::Stub::StopStream(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest& request, ::surveillance::vision::StopResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::surveillance::vision::StopRequest, ::surveillance::vision::StopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StopStream_, context, request, response);
}

void VisionService::Stub::async::StopStream(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest* request, ::surveillance::vision::StopResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::surveillance::vision::StopRequest, ::surveillance::vision::StopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopStream_, context, request, response, std::move(f));
}

void VisionService::Stub::async::StopStream(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest* request, ::surveillance::vision::StopResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopStream_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::surveillance::vision::StopResponse>* VisionService::Stub::PrepareAsyncStopStreamRaw(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::surveillance::vision::StopResponse, ::surveillance::vision::StopRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StopStream_, context, request);
}

::grpc::ClientAsyncResponseReader< ::surveillance::vision::StopResponse>* VisionService::Stub::AsyncStopStreamRaw(::grpc::ClientContext* context, const ::surveillance::vision::StopRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopStreamRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VisionService::Stub::GetStreamStatus(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest& request, ::surveillance::vision::StatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::surveillance::vision::StatusRequest, ::surveillance::vision::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStreamStatus_, context, request, response);
}

void VisionService::Stub::async::GetStreamStatus(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest* request, ::surveillance::vision::StatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::surveillance::vision::StatusRequest, ::surveillance::vision::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStreamStatus_, context, request, response, std::move(f));
}

void VisionService::Stub::async::GetStreamStatus(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest* request, ::surveillance::vision::StatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStreamStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::surveillance::vision::StatusResponse>* VisionService::Stub::PrepareAsyncGetStreamStatusRaw(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::surveillance::vision::StatusResponse, ::surveillance::vision::StatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStreamStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::surveillance::vision::StatusResponse>* VisionService::Stub::AsyncGetStreamStatusRaw(::grpc::ClientContext* context, const ::surveillance::vision::StatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStreamStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VisionService::Stub::GetHealth(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest& request, ::surveillance::vision::HealthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::surveillance::vision::HealthRequest, ::surveillance::vision::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetHealth_, context, request, response);
}

void VisionService::Stub::async::GetHealth(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest* request, ::surveillance::vision::HealthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::surveillance::vision::HealthRequest, ::surveillance::vision::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetHealth_, context, request, response, std::move(f));
}

void VisionService::Stub::async::GetHealth(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest* request, ::surveillance::vision::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetHealth_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::surveillance::vision::HealthResponse>* VisionService::Stub::PrepareAsyncGetHealthRaw(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::surveillance::vision::HealthResponse, ::surveillance::vision::HealthRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetHealth_, context, request);
}

::grpc::ClientAsyncResponseReader< ::surveillance::vision::HealthResponse>* VisionService::Stub::AsyncGetHealthRaw(::grpc::ClientContext* context, const ::surveillance::vision::HealthRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetHealthRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>* VisionService::Stub::ProcessFramesRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>::Create(channel_.get(), rpcmethod_ProcessFrames_, context);
}

void VisionService::Stub::async::ProcessFrames(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::surveillance::vision::FrameRequest,::surveillance::vision::FrameResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::surveillance::vision::FrameRequest,::surveillance::vision::FrameResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_ProcessFrames_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>* VisionService::Stub::AsyncProcessFramesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>::Create(channel_.get(), cq, rpcmethod_ProcessFrames_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>* VisionService::Stub::PrepareAsyncProcessFramesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>::Create(channel_.get(), cq, rpcmethod_ProcessFrames_, context, false, nullptr);
}

::grpc::ClientReader< ::surveillance::vision::Frame>* VisionService::Stub::GetFramesRaw(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::surveillance::vision::Frame>::Create(channel_.get(), rpcmethod_GetFrames_, context, request);
}

void VisionService::Stub::async::GetFrames(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest* request, ::grpc::ClientReadReactor< ::surveillance::vision::Frame>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::surveillance::vision::Frame>::Create(stub_->channel_.get(), stub_->rpcmethod_GetFrames_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::surveillance::vision::Frame>* VisionService::Stub::AsyncGetFramesRaw(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::surveillance::vision::Frame>::Create(channel_.get(), cq, rpcmethod_GetFrames_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::surveillance::vision::Frame>* VisionService::Stub::PrepareAsyncGetFramesRaw(::grpc::ClientContext* context, const ::surveillance::vision::GetFramesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::surveillance::vision::Frame>::Create(channel_.get(), cq, rpcmethod_GetFrames_, context, request, false, nullptr);
}

::grpc::ClientReader< ::surveillance::vision::DetectionEvent>* VisionService::Stub::StreamDetectionsRaw(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::surveillance::vision::DetectionEvent>::Create(channel_.get(), rpcmethod_StreamDetections_, context, request);
}

void VisionService::Stub::async::StreamDetections(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest* request, ::grpc::ClientReadReactor< ::surveillance::vision::DetectionEvent>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::surveillance::vision::DetectionEvent>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamDetections_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::surveillance::vision::DetectionEvent>* VisionService::Stub::AsyncStreamDetectionsRaw(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::surveillance::vision::DetectionEvent>::Create(channel_.get(), cq, rpcmethod_StreamDetections_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::surveillance::vision::DetectionEvent>* VisionService::Stub::PrepareAsyncStreamDetectionsRaw(::grpc::ClientContext* context, const ::surveillance::vision::DetectionStreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::surveillance::vision::DetectionEvent>::Create(channel_.get(), cq, rpcmethod_StreamDetections_, context, request, false, nullptr);
}

VisionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VisionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VisionService::Service, ::surveillance::vision::StreamRequest, ::surveillance::vision::StreamResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VisionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::surveillance::vision::StreamRequest* req,
             ::surveillance::vision::StreamResponse* resp) {
               return service->StartStream(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VisionService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VisionService::Service, ::surveillance::vision::StopRequest, ::surveillance::vision::StopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VisionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::surveillance::vision::StopRequest* req,
             ::surveillance::vision::StopResponse* resp) {
               return service->StopStream(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VisionService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VisionService::Service, ::surveillance::vision::StatusRequest, ::surveillance::vision::StatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VisionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::surveillance::vision::StatusRequest* req,
             ::surveillance::vision::StatusResponse* resp) {
               return service->GetStreamStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VisionService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VisionService::Service, ::surveillance::vision::HealthRequest, ::surveillance::vision::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VisionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::surveillance::vision::HealthRequest* req,
             ::surveillance::vision::HealthResponse* resp) {
               return service->GetHealth(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VisionService_method_names[4],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< VisionService::Service, ::surveillance::vision::FrameRequest, ::surveillance::vision::FrameResponse>(
          [](VisionService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::surveillance::vision::FrameResponse,
             ::surveillance::vision::FrameRequest>* stream) {
               return service->ProcessFrames(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VisionService_method_names[5],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< VisionService::Service, ::surveillance::vision::GetFramesRequest, ::surveillance::vision::Frame>(
          [](VisionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::surveillance::vision::GetFramesRequest* req,
             ::grpc::ServerWriter<::surveillance::vision::Frame>* writer) {
               return service->GetFrames(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VisionService_method_names[6],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< VisionService::Service, ::surveillance::vision::DetectionStreamRequest, ::surveillance::vision::DetectionEvent>(
          [](VisionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::surveillance::vision::DetectionStreamRequest* req,
             ::grpc::ServerWriter<::surveillance::vision::DetectionEvent>* writer) {
               return service->StreamDetections(ctx, req, writer);
             }, this)));
}

VisionService::Service::~Service() {
}

::grpc::Status VisionService::Service::StartStream(::grpc::ServerContext* context, const ::surveillance::vision::StreamRequest* request, ::surveillance::vision::StreamResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VisionService::Service::StopStream(::grpc::ServerContext* context, const ::surveillance::vision::StopRequest* request, ::surveillance::vision::StopResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VisionService::Service::GetStreamStatus(::grpc::ServerContext* context, const ::surveillance::vision::StatusRequest* request, ::surveillance::vision::StatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VisionService::Service::GetHealth(::grpc::ServerContext* context, const ::surveillance::vision::HealthRequest* request, ::surveillance::vision::HealthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VisionService::Service::ProcessFrames(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::surveillance::vision::FrameResponse, ::surveillance::vision::FrameRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VisionService::Service::GetFrames(::grpc::ServerContext* context, const ::surveillance::vision::GetFramesRequest* request, ::grpc::ServerWriter< ::surveillance::vision::Frame>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VisionService::Service::StreamDetections(::grpc::ServerContext* context, const ::surveillance::vision::DetectionStreamRequest* request, ::grpc::ServerWriter< ::surveillance::vision::DetectionEvent>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace surveillance
}  // namespace vision

