# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vision_pb2 as vision__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisionServiceStub(object):
    """Service principal de traitement vidéo
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartStream = channel.unary_unary(
                '/surveillance.vision.VisionService/StartStream',
                request_serializer=vision__pb2.StreamRequest.SerializeToString,
                response_deserializer=vision__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.StopStream = channel.unary_unary(
                '/surveillance.vision.VisionService/StopStream',
                request_serializer=vision__pb2.StopRequest.SerializeToString,
                response_deserializer=vision__pb2.StopResponse.FromString,
                _registered_method=True)
        self.GetStreamStatus = channel.unary_unary(
                '/surveillance.vision.VisionService/GetStreamStatus',
                request_serializer=vision__pb2.StatusRequest.SerializeToString,
                response_deserializer=vision__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/surveillance.vision.VisionService/GetHealth',
                request_serializer=vision__pb2.HealthRequest.SerializeToString,
                response_deserializer=vision__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ProcessFrames = channel.stream_stream(
                '/surveillance.vision.VisionService/ProcessFrames',
                request_serializer=vision__pb2.FrameRequest.SerializeToString,
                response_deserializer=vision__pb2.FrameResponse.FromString,
                _registered_method=True)


class VisionServiceServicer(object):
    """Service principal de traitement vidéo
    """

    def StartStream(self, request, context):
        """Démarrer un stream de caméra
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStream(self, request, context):
        """Arrêter un stream de caméra  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamStatus(self, request, context):
        """Récupérer le statut d'un stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Health check du service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessFrames(self, request_iterator, context):
        """Stream de frames (bidirectionnel)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStream,
                    request_deserializer=vision__pb2.StreamRequest.FromString,
                    response_serializer=vision__pb2.StreamResponse.SerializeToString,
            ),
            'StopStream': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStream,
                    request_deserializer=vision__pb2.StopRequest.FromString,
                    response_serializer=vision__pb2.StopResponse.SerializeToString,
            ),
            'GetStreamStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamStatus,
                    request_deserializer=vision__pb2.StatusRequest.FromString,
                    response_serializer=vision__pb2.StatusResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=vision__pb2.HealthRequest.FromString,
                    response_serializer=vision__pb2.HealthResponse.SerializeToString,
            ),
            'ProcessFrames': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessFrames,
                    request_deserializer=vision__pb2.FrameRequest.FromString,
                    response_serializer=vision__pb2.FrameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'surveillance.vision.VisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('surveillance.vision.VisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VisionService(object):
    """Service principal de traitement vidéo
    """

    @staticmethod
    def StartStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surveillance.vision.VisionService/StartStream',
            vision__pb2.StreamRequest.SerializeToString,
            vision__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surveillance.vision.VisionService/StopStream',
            vision__pb2.StopRequest.SerializeToString,
            vision__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surveillance.vision.VisionService/GetStreamStatus',
            vision__pb2.StatusRequest.SerializeToString,
            vision__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surveillance.vision.VisionService/GetHealth',
            vision__pb2.HealthRequest.SerializeToString,
            vision__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/surveillance.vision.VisionService/ProcessFrames',
            vision__pb2.FrameRequest.SerializeToString,
            vision__pb2.FrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
